version: '3.8'

services:
  flaskblog:
    image: flask_emulator_blog
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    ports:
      - "8000:8000"
    environment:
      EMAIL_USER: "monkeyboyfresh_bro@yahoo.com"
      EMAIL_PASSWORD: "pass"
      FLASK_SECRET_KEY: "your_secret_key"
      APP_STATIC_PATH: "/config/static"
    volumes:
      - .:/app
      - ./config:/config
      - /usr/bin/git:/usr/bin/git
    container_name: luna_edge
    restart: unless-stopped
